apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgressrv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgressrv
    spec:
      containers:
        - name: postgressrv
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: dbsercret
                   key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim