apiVersion: v1
kind: Service
metadata:
  name: jobvacancy-svc
  labels:
    app: jobvacancy
spec:
  selector:
    app: jobvacancy
  type: NodePort
  ports:
    - port: 3000
      name: http
      targetPort: 3000
      protocol: TCP